---
driver:
  name: digitalocean
  digitalocean_client_id: <%= ENV['DIGITALOCEAN_CLIENT_ID'] %>
  digitalocean_api_key: <%= ENV['DIGITALOCEAN_API_KEY'] %>
  ssh_key: <%= ChefDk::Helpers.private_key_file %>
  ssh_key_ids: <%= ChefDk::Helpers.ssh_key_ids %>
